import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

part 'database.g.dart';

// Data class for data points
class DataPoints extends Table {
  IntColumn get id => integer().autoIncrement()();
  RealColumn get latitude => real()();
  RealColumn get longitude => real()();
  TextColumn get pointId => text()();
}

@DriftDatabase(tables: [DataPoints])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  // Get all data points
  // Note: DataPoint is generated by Drift from the DataPoints table
  Future<List<DataPoint>> getAllDataPoints() async {
    return await (select(dataPoints)..orderBy([(t) => OrderingTerm.asc(t.id)])).get();
  }

  // Get closest points to a location
  // Note: DataPoint is generated by Drift from the DataPoints table
  Future<List<DataPoint>> getClosestPoints(double latitude, double longitude, int limit) async {
    // Calculate distance for each point and sort by distance
    // Using simple Euclidean distance approximation
    final query = select(dataPoints);
    final allPoints = await query.get();
    
    // Calculate distances and sort
    final pointsWithDistance = allPoints.map((point) {
      final latDiff = (point.latitude - latitude).abs();
      final lngDiff = (point.longitude - longitude).abs();
      final distance = (latDiff * latDiff + lngDiff * lngDiff);
      return MapEntry(distance, point);
    }).toList();
    
    pointsWithDistance.sort((a, b) => a.key.compareTo(b.key));
    
    return pointsWithDistance.take(limit).map((e) => e.value).toList();
  }

  // Insert multiple points in batch
  // Note: DataPointsCompanion is generated by Drift from the DataPoints table
  Future<void> insertDataPoints(List<DataPointsCompanion> points) async {
    await batch((batch) {
      batch.insertAll(dataPoints, points);
    });
  }

  // Get count of data points
  Future<int> getDataPointCount() async {
    final count = await (selectOnly(dataPoints)..addColumns([dataPoints.id.count()])).getSingle();
    return count.read(dataPoints.id.count()) ?? 0;
  }

  // Clear all data points
  Future<void> clearAllDataPoints() async {
    await delete(dataPoints).go();
  }
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'data_points.db'));
    return NativeDatabase.createInBackground(file);
  });
}
